
/*""""""""""""""""""""""""""""""""""""""""""""""""""""""""*/
CREATE TABLE tipo (
id_tipo SERIAL PRIMARY KEY,
tipo varchar(100)
)

INSERT INTO tipo	


--""""""""""""""""""""""""""""""""""""""""""""""""""""""""
???


INSERT INTO marca 
???

--""""""""""""""""""""""""""""""""""""""""""""""""""""""""
???


INSERT INTO material 
???


--===================<< Criação da VIEW >> ================

CREATE VIEW   Marcas_materiais (
	SELECT ?
	
)

--""""""""""""""""""""""""""""""""""""""""""""""""""""""""

CREATE VIEW   Materiais_tipo_Marca(
	SELECT ?

)


--##########################################################

SELECT FROM ?